export const events = [
  {
    title: "Web Summit 2025",
    image: "/images/event1.png",
    slug: "web-summit-2025",
    location: "Lisbon, Portugal",
    date: "Nov 12 - Nov 14, 2025",
    time: "09:00 AM",
  },
  {
    title: "React Conf 2025",
    image: "/images/event2.png",
    slug: "react-conf-2025",
    location: "Las Vegas, USA",
    date: "Dec 04 - Dec 06, 2025",
    time: "10:00 AM",
  },
  {
    title: "JavaScript Summit",
    image: "/images/event3.png",
    slug: "javascript-summit-2025",
    location: "San Francisco, USA",
    date: "Jan 15 - Jan 17, 2026",
    time: "08:30 AM",
  },
  {
    title: "Tech Hackathon 2025",
    image: "/images/event4.png",
    slug: "tech-hackathon-2025",
    location: "New York, USA",
    date: "Dec 20 - Dec 22, 2025",
    time: "11:00 AM",
  },
  {
    title: "Developer Conference Asia",
    image: "/images/event5.png",
    slug: "devconf-asia-2025",
    location: "Singapore",
    date: "Jan 10 - Jan 12, 2026",
    time: "09:00 AM",
  },
  {
    title: "Frontend Masters Camp",
    image: "/images/event6.png",
    slug: "frontend-masters-2025",
    location: "Berlin, Germany",
    date: "Feb 01 - Feb 03, 2026",
    time: "10:00 AM",
  },
];
